name: Test plugin

on:
  push:
  # pull_request:

  schedule:
    - cron: "0 6 * * 6" # Saturday at 6am

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Yazi ${{ matrix.yazi }}
    runs-on: ubuntu-26.04 # tmux in ubuntu-latest is too old for latest yazi, use next

    strategy:
      fail-fast: false
      matrix:
        yazi:
          - release-latest
          - release-v26.9.1
          - release-v26.8.15
          # - release-nightly
          # - main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install binary Yazi ${{ matrix.yazi }}
        if: matrix.yazi != 'main'
        run: |
          echo "Installing binary Yazi ${{ matrix.yazi }}"
          TARGET="yazi-x86_64-unknown-linux-gnu"
          RELEASE="${{ matrix.yazi }}"
          TAG="${RELEASE/release-/}"
          URL="https://github.com/sxyazi/yazi/releases/download/$TAG/$TARGET.zip"
          if [[ $TAG == "latest" ]]; then
            URL="https://github.com/sxyazi/yazi/releases/latest/download/$TARGET.zip"
          fi
          YAZI_ZIP="$RUNNER_TEMP/yazi.zip"
          curl -fsSL "$URL" -o "$YAZI_ZIP"
          unzip -q "$YAZI_ZIP" -d "$RUNNER_TEMP" && rm "$YAZI_ZIP"
          install -D -t ~/.local/bin "$RUNNER_TEMP/$TARGET"/{yazi,ya} && rm -rf "$RUNNER_TEMP/$TARGET"

      - name: Get latest Yazi commit
        id: yazi-commit
        if: matrix.yazi == 'main'
        run: |
          echo "commit=$(git ls-remote https://github.com/sxyazi/yazi.git refs/heads/main | cut -f1)" >> "$GITHUB_OUTPUT"

      - name: Restore cargo cache
        uses: actions/cache/restore@v6
        id: cache-cargo-restore
        if: matrix.yazi == 'main'
        with:
          path: &cache_paths |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/target/yazi
          key: cargo-install-yazi-${{ runner.os }}-${{ runner.arch }}-${{ steps.yazi-commit.outputs.commit }}
        
      - name: Install Yazi main
        if: matrix.yazi == 'main' && steps.cache-cargo-restore.outputs.cache-hit != 'true'
        run: |
          echo "Installing latest Yazi from git"
          export CARGO_TARGET_DIR="$HOME/.cargo/target/yazi"
          mkdir -p ~/.cargo/target
          cargo install --force \
            --git https://github.com/sxyazi/yazi.git \
            --branch main \
            yazi-build

      - name: Save cargo cache
        uses: actions/cache/save@v6
        if: always() && matrix.yazi == 'main' && steps.cache-cargo-restore.outputs.cache-hit != 'true'
        with:
          path: *cache_paths
          key: ${{ steps.cache-cargo-restore.outputs.cache-primary-key }}

      - name: Install runtime dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet tmux
          
      - name: Check versions
        run: |
          cargo --version
          yazi --version
          ya --version
          tmux -V
          xmlstarlet --version

      - name: Install recents.yazi plugin
        run: |
          mkdir -p ~/.config/yazi/plugins
          ln -s "$PWD" ~/.config/yazi/plugins/recents.yazi

          ls -alh ~/.config/yazi/plugins
          ls ~/.config/yazi/plugins/recents.yazi

          # configure plugin with instructions from README
          function find_toml_content() {
            sed -n '/'"$1"'/,/```$/p' README.md | sed -n '/```toml/,/```$/{//!p}'
          }
          find_toml_content "vfs.toml" > ~/.config/yazi/vfs.toml
          find_toml_content "yazi.toml" > ~/.config/yazi/yazi.toml

      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh
